name: Leonie's BÃ¼cher Rezensionen
title: null



layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes

encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"