title               : Leonie's BÃ¼cher Rezensionen


layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
theme               : minima
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"